# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
workflows:
  version: 2
  test:
    jobs: 
      - test-2.7
      - test-3.5
      - test-3.6
jobs:
  test-2.7: &template
    environment:
      COLUMNS: 160
      PATH: /root/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    docker:
      - image: circleci/python:2.7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            pip install -q --user --upgrade -r requirements.txt
      - run:
          name: setup
          command: |
            make setup
      # run tests!
      - run:
          name: run tests
          command: |
            make tests

  test-3.5: 
    <<: *template
    docker:
      - image: python:3.5
  test-3.6:
    <<: *template
    docker: 
      - image: python:3.6
          
